use crate::state::domain::VersionInfo;
use ratatui::widgets::ListState;
use std::time::Instant;
use throbber_widgets_tui::ThrobberState;

pub struct UiState {
    pub selected_index: usize,
    pub selected_nix_file_index: usize,
    pub selected_output_index: usize,
    pub is_adding_input: bool,
    pub is_adding_package: bool,
    pub is_searching_packages: bool,
    pub is_showing_package_details: bool,
    pub package_search_query: String,
    pub package_search_state: ListState,
    pub command_log_state: ListState,
    pub throbber_state: ThrobberState,
    pub new_input_name: String,
    pub new_input_url: String,
    pub input_cursor: usize,
    pub package_fetch_error: Option<String>,
    pub package_search_error: Option<String>,
    pub fetching_package_details: bool,
    pub last_search_query: String,
    pub last_search_time: Instant,
    pub shell_package_list_state: ratatui::widgets::TableState,
    pub is_selecting_version: bool,
    pub is_fetching_versions: bool,
    pub version_fetch_error: Option<String>,
    pub version_list_state: ListState,
    pub selected_package_name: Option<String>,
    pub selected_version: Option<VersionInfo>,
    pub package_table_state: ratatui::widgets::TableState,
    pub input_table_state: ratatui::widgets::TableState,
    pub package_fetch_id: usize,
    pub selected_packages: std::collections::HashSet<String>,
    pub selected_shell_packages: std::collections::HashSet<String>,
    pub pinned_packages: std::collections::HashSet<String>,
    pub show_help: bool,
    pub show_templates: bool,
    pub is_saving_shell_template: bool,
    pub is_confirming_template_overwrite: bool,
    pub pending_template_name: Option<String>,
    pub new_template_filename: String,
    pub new_template_description: String,
    pub template_cursor: usize,
    pub template_list_state: ratatui::widgets::TableState,
    pub templates: Vec<(String, String)>,
}

impl Default for UiState {
    fn default() -> Self {
        Self {
            selected_index: 2,
            selected_nix_file_index: 0,
            selected_output_index: 0,
            is_adding_input: false,
            is_adding_package: false,
            is_searching_packages: false,
            is_showing_package_details: false,
            package_search_query: String::new(),
            package_search_state: ListState::default(),
            command_log_state: ListState::default(),
            throbber_state: ThrobberState::default(),
            new_input_name: String::new(),
            new_input_url: String::new(),
            input_cursor: 0,
            package_fetch_error: None,
            package_search_error: None,
            fetching_package_details: false,
            last_search_query: String::new(),
            last_search_time: Instant::now(),
            shell_package_list_state: ratatui::widgets::TableState::default(),
            is_selecting_version: false,
            is_fetching_versions: false,
            version_fetch_error: None,
            version_list_state: ListState::default(),
            selected_package_name: None,
            selected_version: None,
            package_table_state: ratatui::widgets::TableState::default(),
            input_table_state: ratatui::widgets::TableState::default(),
            package_fetch_id: 0,
            selected_packages: std::collections::HashSet::new(),
            selected_shell_packages: std::collections::HashSet::new(),
            pinned_packages: std::collections::HashSet::new(),
            show_help: false,
            show_templates: false,
            is_saving_shell_template: false,
            is_confirming_template_overwrite: false,
            pending_template_name: None,
            new_template_filename: String::new(),
            new_template_description: String::new(),
            template_cursor: 0,
            template_list_state: ratatui::widgets::TableState::default(),
            templates: Vec::new(),
        }
    }
}
